	-- =========================================
-- Create table template
-- =========================================
USE messenger_db
GO

CREATE TABLE users(
    Id UNIQUEIDENTIFIER CONSTRAINT PK_users_Id PRIMARY KEY DEFAULT NEWID(),
	Login NVARCHAR(32) CONSTRAINT UQ_users_Login UNIQUE NOT NULL,
	Password NVARCHAR(128) NOT NULL,
    LastActiveDate DATETIMEOFFSET(2),
    --LastActiveDate DATETIMEOFFSET(7),
    --ActivityStatus INT NOT NULL,
    ActivityStatus TINYINT NOT NULL,
    Avatar NVARCHAR(2038)
)
GO

CREATE TABLE chats(
    Id UNIQUEIDENTIFIER CONSTRAINT PK_chats_Id PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Title NVARCHAR(32) NOT NULL,
    OwnerId UNIQUEIDENTIFIER CONSTRAINT FK_chats_OwnerId_users_Id FOREIGN KEY (OwnerId) REFERENCES users(Id) NOT NULL,
	Type TINYINT NOT NULL,
	--Type INT NOT NULL,
    IsPersonal BIT NOT NULL
)
GO

CREATE SEQUENCE messagesUSN 
	AS BIGINT
    START WITH 0  
    INCREMENT BY 1  
GO  

CREATE TABLE messages(
    Id UNIQUEIDENTIFIER CONSTRAINT PK_messages_Id PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
	USN BIGINT CONSTRAINT UQ_messages_USN UNIQUE NOT NULL DEFAULT NEXT VALUE FOR messagesUSN,
    DispatchDate DATETIMEOFFSET(2) NOT NULL,
    --DispatchDate DATETIMEOFFSET(7) NOT NULL,
	MessageText NVARCHAR(2038),
    Type TINYINT NOT NULL,
    --Type INT NOT NULL,
    ContentUri NVARCHAR(2038)
)
GO

CREATE TABLE contactsLists(
    Id UNIQUEIDENTIFIER CONSTRAINT PK_contactsLists_Id PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    OwnerId UNIQUEIDENTIFIER CONSTRAINT FK_contactsLists_OwnerId_users_Id FOREIGN KEY (OwnerId) REFERENCES users(Id) NOT NULL,
    UserId UNIQUEIDENTIFIER CONSTRAINT FK_contactsLists_UserId_users_Id FOREIGN KEY (UserId) REFERENCES users(Id) NOT NULL,
    IsBlocked BIT NOT NULL
)
GO

CREATE TABLE chatsParticipants(
    Id UNIQUEIDENTIFIER CONSTRAINT PK_chatsParticipants_Id PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    ChatId UNIQUEIDENTIFIER CONSTRAINT FK_chatsParticipants_ChatId_chats_Id FOREIGN KEY (ChatId) REFERENCES chats(Id) NOT NULL,
    UserId UNIQUEIDENTIFIER CONSTRAINT FK_chatsParticipants_UserId_users_Id FOREIGN KEY (UserId) REFERENCES users(Id) NOT NULL,   
)
GO

CREATE TABLE messagesInChats(
    Id UNIQUEIDENTIFIER CONSTRAINT PK_messagesInChats_Id PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    MessageId UNIQUEIDENTIFIER CONSTRAINT FK_messagesInChats_MessageId_messages_Id FOREIGN KEY (MessageId) REFERENCES messages(Id) NOT NULL,
    ChatId UNIQUEIDENTIFIER CONSTRAINT FK_messagesInChats_ChatId_chats_Id FOREIGN KEY (ChatId) REFERENCES chats(Id) NOT NULL,
    FromUserId UNIQUEIDENTIFIER CONSTRAINT FK_messagesInChats_FromUserId_users_Id FOREIGN KEY (FromUserId) REFERENCES users(Id) NOT NULL,
    ToUserId UNIQUEIDENTIFIER CONSTRAINT FK_messagesInChats_ToUserId_users_Id FOREIGN KEY (ToUserId) REFERENCES users(Id) NOT NULL,
    IsRead BIT NOT NULL
)
GO
